version: '3.7'

services:
  url-shortener-api:
    image: url-shortener-api
    build:
      context: url-shortener-api
      dockerfile: ./Dockerfile
    volumes:
       - './logs:/logs'
    ports:
      - "8080:8080"
    restart: always
    environment:
       - "MONGO_HOST=url_shortener_db"
    networks:
      - url_shortener_network
  mongodb:
    image: "mongo"
    container_name: "url_shortener_db"
    ports:
      - "27017:27017"
    networks:
      - url_shortener_network
  promtail:
    image: grafana/promtail:2.1.0
    container_name: promtail
    volumes:
      - ./docker/promtail/promtail-config.yaml:/etc/promtail/docker-config.yaml
      - ./logs:/var/log
    command: "--config.file=/etc/promtail/docker-config.yaml"
    networks:
      - url_shortener_network
  loki:
    image: grafana/loki:2.1.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - url_shortener_network
  grafana:
    image: grafana/grafana:7.3.6
    container_name: grafana
    volumes:
      - ./docker/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./docker/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_USERS_DEFAULT_THEME=dark
    ports:
      - "3000:3000"
    depends_on:
      - loki
    networks:
      - url_shortener_network
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - "9090:9090"
    networks:
      - url_shortener_network
networks:
  url_shortener_network:
    name: url_shortener_network

