version: '3.7'

services:
  url-shortener-api:
    image: url-shortener-api
    build:
      context: url-shortener-api
      dockerfile: ./Dockerfile
    volumes:
       - ./logs/urlshortenerapi.log:/logs/urlshortenerapi.log
    ports:
      - "8080:8080"
    restart: always
  mongodb:
    image: "mongo"
    container_name: "url_shortener_db"
    ports:
      - "27017:27017"
  promtail:
    image: grafana/promtail:2.1.0
    container_name: promtail
    volumes:
      - ./docker/promtail/promtail-config.yaml:/etc/promtail/docker-config.yaml
      - ./logs/urlshortenerapi.log:/var/log/urlshortenerapi.log
    command: "--config.file=/etc/promtail/docker-config.yaml"
  loki:
    image: grafana/loki:2.1.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
  grafana:
    image: grafana/grafana:7.3.6
    container_name: grafana
    volumes:
      - ./docker/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./docker/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_USERS_DEFAULT_THEME=light
    ports:
      - "3000:3000"
    depends_on:
      - loki



