
apiVersion: 1

datasources:
  - name: loki-datasource
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
  - name: prometheus-datasource
    type: prometheus
    access: proxy
    url: http://prometheus:9090
