global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'url-shortener-api'
    metrics_path: '/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['url-shortener-api:8080']
        labels:
          application: 'url-shortener-api using micronaut'