micronaut:
  application:
    name: urlShortenerApi
netty:
  default:
    allocator:
      max-order: 3
mongodb:
  uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/urldb
  package-names: com.urlshortener.infraestructure.persistence
